In [ ]:
import yfinance as yf

In [ ]:
msft = yf.Ticker("MSFT")
print(msft)

In [4]:
# msft.info
msft.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13,0.056108,0.064359,0.056108,0.061608,1031788800,0.0,0.0
1986-03-14,0.061608,0.064909,0.061608,0.063809,308160000,0.0,0.0
1986-03-17,0.063809,0.065459,0.063809,0.064909,133171200,0.0,0.0
1986-03-18,0.064909,0.065459,0.062708,0.063258,67766400,0.0,0.0
1986-03-19,0.063258,0.063809,0.061608,0.062158,47894400,0.0,0.0
...,...,...,...,...,...,...,...
2021-06-30,270.690002,271.359985,269.600006,270.899994,21656500,0.0,0.0
2021-07-01,269.609985,271.839996,269.600006,271.600006,16725300,0.0,0.0
2021-07-02,272.820007,278.000000,272.500000,277.649994,26458000,0.0,0.0
2021-07-06,278.029999,279.369995,274.299988,277.660004,31565600,0.0,0.0
2021-07-07,279.399994,280.690002,277.149994,279.929993,23236200,0.0,0.0

In [6]:
dir(yf.Tickers)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'download',
 'history']